name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
    #pull_request:
    #branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SonarQube Scan
        run: |
                mvn clean \
                    -Dcheckstyle.skip=true \
                    -Dmaven.javadoc.skip=true \
                    org.jacoco:jacoco-maven-plugin:prepare-agent \
                    package \
                    verify -Dgpg.skip=true \
                    org.jacoco:jacoco-maven-plugin:report \
                    org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                    -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
                    -Dsonar.organization=xips-project \
                    --file pom.xml -B --no-transfer-progress
              env:
                SONAR_TOKEN: 99ca41e7cdcf8d690af802b3917bbe26f2c716d8
                SONAR_HOST_URL: https://sonarcloud.io
      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
                SONAR_TOKEN: 99ca41e7cdcf8d690af802b3917bbe26f2c716d8
                SONAR_HOST_URL: https://sonarcloud.io
        with:
                scanMetadataReportFile: target/sonar/report-task.txt