on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Triggering SonarQube analysis as results of it are required by Quality Gate check.
      - name: SonarQube Scan
        run: |
          mvn clean \
                -Dcheckstyle.skip=true \
                -Dmaven.javadoc.skip=true \
                org.jacoco:jacoco-maven-plugin:prepare-agent \
                package \
                verify -Dgpg.skip=true \
                org.jacoco:jacoco-maven-plugin:report \
                org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
                -Dsonar.organization=robtimus-github \
                --file pom.xml -B --no-transfer-progress
        env:
          SONAR_TOKEN: ${{ secrets.SonarCloudToken }}
          SONAR_HOST_URL: https://sonarcloud.io

      # Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
          SONAR_TOKEN: 99ca41e7cdcf8d690af802b3917bbe26f2c716d8
          SONAR_HOST_URL: https://sonarcloud.io

      # Optionally you can use the output from the Quality Gate in another step.
      # The possible outputs of the `quality-gate-status` variable are `PASSED`, `WARN` or `FAILED`.
      - name: "Example show SonarQube Quality Gate Status value"
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
